use_frameworks!

target 'InsidedCollectionView_Example' do
  pod 'InsidedCollectionView', :path => '../'

  target 'InsidedCollectionView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
